# Generated by Django 5.0.1 on 2025-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('medecin', 'Médecin'), ('admin', 'Administrateur')], default='patient', max_length=10),
        ),
    ]
