# Generated by Django 5.0.1 on 2025-07-13 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dossiermedical_entreedossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 0, 0)),
            preserve_default=False,
        ),
    ]
