# Generated by Django 5.0.1 on 2025-06-09 12:45

import consultations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='lien_visio',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='room_name',
            field=models.CharField(default=consultations.models.generate_room_name, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='médecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_medecin', to=settings.AUTH_USER_MODEL),
        ),
    ]
