# Generated by Django 5.0.1 on 2025-06-09 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_rendezvous_lien_visio_rendezvous_room_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='consultation',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='auteur',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(default='', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
