# Generated by Django 5.0.1 on 2025-07-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_ordonnance_consultation_ordonnance_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='salle_ouverte',
            field=models.BooleanField(default=False),
        ),
    ]
