# Generated by Django 5.0.1 on 2025-07-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rendezvous_salle_ouverte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='médecin',
            new_name='medecin',
        ),
    ]
